#:schema ./.config.schema.json

root_file_name = "README.md"

[properties.status]
type = "enum"
values = ["open", "closed"]
default = "open"

[properties.priority]
type = "number"
min = 0
max = 100
default = 999

[properties.kind]
type = "enum"
values = ["bug", "feature", "test"]
default = "feature"

[properties.tags]
type = "array"
